jaeger:
  enabled: false

components:
  flagd:
    env:
      - name: FLAGD_PRODUCT_CATALOG_FAILURE
        value: "true"
      - name: FLAGD_RECOMMENDATION_CACHE_FAILURE
        value: "true"

opentelemetry-collector:
  config:
    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      batch: {}

      tail_sampling:
        decision_wait: 10s
        num_traces: 10000
        expected_new_traces_per_sec: 2000
        policies:
          - name: drop_errors_policy
            type: status_code
            status_code: {status_codes: [ERROR]}
          - name: latency_policy
            type: latency
            latency: {threshold_ms: 1500}
          - name: probabilistic_policy
            type: probabilistic
            probabilistic: {sampling_percentage: 5.0}

    exporters:
      otlp/standalone:
        endpoint: "jaeger-standalone.default.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, tail_sampling, batch]
          exporters:
            - otlp/standalone
            - span_metrics